exports.companies = require('./company-pgdb')
exports.admins = require('./admin-pgdb')
exports.employees = require('./employee-pgdb')
exports.requests = require('./request-pgdb')
exports.users = require('./user-pgdb')